USE sakila;

-- 1. List the number of films per category
SELECT c.name AS Category, COUNT(f.film_id) AS Number_of_films FROM sakila.category as c
JOIN sakila.film_category as f
ON c.category_id = f.category_id
GROUP BY Category;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id AS StoreID, c.city as City, cy.country as Country FROM sakila.store as s
JOIN sakila.address as a
ON s.address_id = a.address_id
JOIN sakila.city as c
ON c.city_id = a.city_id
JOIN sakila.country as cy
ON cy.country_id = c.country_id;

-- 3. Calculate the total revenue generated by each store in dollars
SELECT s.store_id as store, COUNT(p.amount) as total_revenue FROM sakila.customer as c
JOIN sakila.store as s
ON c.store_id = s.store_id
JOIN sakila.payment as p
ON p.customer_id = c.customer_id
GROUP BY store;

-- 4. Determine the average running time of films for each category
SELECT c.name AS Category, AVG(f.length) AS Average_length FROM sakila.category AS c
JOIN sakila.film_category as fc
ON c.category_id = fc.category_id
JOIN sakila.film as f
ON fc.film_id = f.film_id
GROUP BY Category;